
project_id = "vetstaxdcukdtsfhuxsv"

[functions.create-checkout]
  verify_jwt = true

[functions.payfast-payment]
  verify_jwt = false

[functions.blockchain-explorer-api]
  verify_jwt = false

[functions.sync-fnb-balance]
  verify_jwt = true

[functions.sync-blockchain-tx]
  verify_jwt = true
