// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vetstaxdcukdtsfhuxsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldHN0YXhkY3VrZHRzZmh1eHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTAyNTQsImV4cCI6MjA2NTQ4NjI1NH0.TOXR-mP7-dncDw7tusG8TB3svQ_zgPk83MGR9Vm21ys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);